org: redahmeid
app: splitter
service: splitter
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hours:
    handler: handler.hours
    events:
      - httpApi:
          path: /hours
          method: get
  days:
    handler: handler.days
    events:
      - httpApi:
          path: /days
          method: get
plugins:
  - serverless-python-requirements
 
custom:
  pythonRequirements:
    dockerizePip: non-linux
    

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'